server:
  port: 9000

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/apirest?creteDatabaseIfNotExist=true&userUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    user: root
    password: admin
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
